apiVersion: v1
kind: Service
metadata:
  name: mynodeportapp-service

spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30007
  selector:
    app: myfirstapp


